sillsdev/machine.py

.github/workflows/ci.yml, dockerfile, machine/jobs/clearml_shared_file_service.py, machine/translation/huggingface/hugging_face_nmt_engine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/24)
=> Docker fixes

.github/workflows/ci.yml, poetry.lock, pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/38)
=> add codecov

machine/jobs/huggingface/hugging_face_nmt_model_factory.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/55)
=> enforce upper bound on max steps

.vscode/launch.json, machine/jobs/clearml_shared_file_service.py, machine/jobs/settings.yaml, machine/jobs/shared_file_service.py, machine/translation/huggingface/hugging_face_nmt_engine.py, machine/translation/huggingface/hugging_face_nmt_model_trainer.py
I added sacremoses normalization before training and before pretranslation. I also made sure that `pretranslate.trg.json` makes use of the `shared_file_uri` to ensure it ends up in the same directory as `pretranslate.src.json`. There's also a small fix I made to `launch.json` because I was getting an error that the build options were not valid json.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/96)
=> use sacremoses normalizer, ensure pretranslate.src.json and pretranslate.trg.json use same directory

.vscode/settings.json, machine/jobs/build_nmt_engine.py, machine/jobs/huggingface/hugging_face_nmt_model_factory.py, machine/jobs/nmt_engine_build_job.py, machine/jobs/shared_file_service.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/99)
=> Add option to save the model during build job

machine/jobs/build_nmt_engine.py, machine/jobs/thot/thot_smt_model_factory.py, machine/jobs/thot/thot_word_alignment_model_factory.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/120)
=> small fixes

pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/132)
=> Update version to 1.2.0

machine/translation/huggingface/hugging_face_nmt_engine.py, machine/translation/huggingface/hugging_face_nmt_model_trainer.py
and a config issue.
This is to resolve the final issues for migrating to the newer version of Transformers, etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/140)
=> Fix moses punct

machine/jobs/settings.yaml, machine/jobs/word_alignment_build_job.py
Changes:
* Switch to camelCase in output
* Revert url in settings to enable test WA run
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/158)
=> Small fixes for WA

machine/jobs/settings.yaml
It's finally approved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/162)
=> change to SDPA

samples/paratext_usfm.ipynb
Fixes https://github.com/sillsdev/machine.py/issues/163
Let me know if more examples should be added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/172)
=> Updates to paratext_usfm.ipynb

pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/177)
=> Update machine library to 1.6.3

machine/corpora/place_markers_usfm_update_block_handler.py, tests/corpora/test_place_markers_usfm_update_block_handler.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/182)
=> Adjust embeds to be placed directly before empty end-of-verse paragraph markers

tests/corpora/test_place_markers_usfm_update_block_handler.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/186)
=> Add missing comma in marker placement test

pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/192)
=> Update library to version 1.7.2

machine/corpora/paratext_project_text_updater_base.py, machine/corpora/update_usfm_parser_handler.py, tests/corpora/test_update_usfm_parser_handler.py
Fixes https://github.com/sillsdev/machine.py/issues/173
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/194)
=> Port beginning-of-book remark capability

pyproject.toml
In support of https://github.com/sillsdev/silnlp/issues/758
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/196)
=> Update library version to 1.7.3

machine/corpora/usfm_text_base.py, tests/corpora/test_usfm_memory_text.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/200)
=> Properly include paragraph markers in row text

pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/209)
=> Update machine library to 1.7.4

dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/215)
=> Remove unused library from dockerfile

machine/scripture/verse_ref.py, tests/scripture/test_versification.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/217)
=> Fix type for Russian versifications

pyproject.toml
Non-urgent, but we should release so that the fixes for the custom style sheet are accessible in silnlp.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/233)
=> Update library version to 1.8.3
