machine/jobs/build_nmt_engine.py, machine/jobs/clearml_shared_file_service.py
I added a try except block that will first log any error and then, if it's running on clearml, will call `mark_failed()` with the error message as the `status_reason`. This `status_reason` can then be accessed by machine to pass along to the user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/29)
=> catch all errors and mark clearml task as failed with status_reason

machine/jobs/huggingface/hugging_face_nmt_model_factory.py, machine/translation/huggingface/hugging_face_nmt_engine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/45)
=> Set HuggingFaceNmtEngine to not truncate by default

machine/translation/huggingface/hugging_face_nmt_model_trainer.py
I changed the code so that it doesn't assume the project root directory is the same as the current working directory when loading a tokenizer from the custom_normalizer directory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/48)
=> Fix path issue for loading from custom_normalizer directory

machine/translation/huggingface/hugging_face_nmt_engine.py, tests/translation/huggingface/test_hugging_face_nmt_engine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/50)
=> Raise error when passing an invalid lang code to HuggingFaceNmtEngine

machine/jobs/build_nmt_engine.py, machine/translation/huggingface/hugging_face_nmt_model_trainer.py
This PR ensures that we catch exceptions caused by stopping a clearml task without reraising the exception or marking the task as failed. Also, the `check_canceled()` function is now called before progress updates are made in the `_ProgressCallback` methods rather than after.
In addition, I removed the `stopping` status in the `check_canceled()` function since it's not listed under `task_status_enum`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/57)
=> handle stopped tasks without throwing error

machine/corpora/usfm_file_text.py, machine/corpora/usfm_zip_text.py, tests/corpora/test_usfm_file_text.py, tests/testutils/data/usfm/Tes/04LEVTes.SFM
When retrieving the book abbreviation from the \id marker in a usfm file, convert it to uppercase, so that extracting the corpora will not result in blank output when the book id in the usfm file is lowercase.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/60)
=> convert book abbreviation in \id marker to uppercase

machine/translation/huggingface/hugging_face_nmt_engine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/63)
=> Better error messages for #62

machine/translation/thot/thot_smt_model.py, machine/translation/thot/thot_utils.py, machine/translation/thot/thot_word_alignment_model.py, poetry.lock, pyproject.toml, tests/corpora/test_text_file_text_corpus.py, tests/jobs/test_nmt_engine_build_job.py, tests/translation/thot/test_thot_fast_align_word_alignment_model.py, tests/translation/thot/test_thot_smt_model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/68)
=> Correctly handle corrupted SMT models

machine/jobs/huggingface/hugging_face_nmt_model_factory.py, machine/jobs/nmt_model_factory.py, tests/jobs/test_nmt_engine_build_job.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/69)
=> Remove obsolete code from NmtModelFactory

machine/translation/thot/thot_smt_model.py, tests/translation/thot/test_thot_smt_model.py
The `source_start_index` and `source_end_index` of `WordGraphArc`s seem to be 1-indexed, which was leading to index out of range errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/77)
=> Fixed off-by-one errors in _create_word_graph

machine/scripture/parse.py, tests/scripture/test_parse.py
Update get_chapters to work more similarly to get_books.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/80)
=> Update get_chapters to more similarly to get_books

machine/scripture/parse.py, tests/scripture/test_parse.py
Create more robust check for old vs new book selection syntax and give more descriptive error messages when syntaxes are mixed. Previous version allowed some things, e.g. ranges of books, to be used with the comma-separated syntax, but not others, e.g. chapter selections, and that was confusing. This version allows only basic book and testament selection to be separated with commas, which matches the get_books function, and adds error messages that tell the user they may have mixed syntaxes when there is a parsing error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/87)
=> Create more robust check for old vs new book selection syntax

.vscode/launch.json, .vscode/settings.json, machine/jobs/build_nmt_engine.py, machine/jobs/huggingface/hugging_face_nmt_model_factory.py, machine/jobs/nmt_engine_build_job.py, machine/jobs/settings.yaml, tests/jobs/test_nmt_engine_build_job.py
- fixes #86
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/88)
=> Restrict build options to only update model hyperparameters

machine/corpora/usfm_file_text.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/90)
=> Update error message to include filename

machine/jobs/settings.yaml
On a 3090 it saves 2 minutes per run.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/92)
=> swap out 600M param model for tiny for faster startup

machine/corpora/usfm_token.py, tests/corpora/test_usfm_file_text.py, tests/corpora/test_usfm_tokenizer.py, tests/testutils/data/usfm/Tes/41MATTes.SFM
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/93)
=> Add test for default attributes in USFM

machine/scripture/parse.py, tests/scripture/test_parse.py
@Enkidu93 For the first section, I thought my original error messages didn't make a ton of sense, so I rewrote and combined them. I also updated the `BOOK_RANGE` and `CHAPTER_SELECTION` regexes to allow subtraction so that I could take out the subtraction check right before.
I also decided to just take out the ability to add "chapter 0" because I don't think anyone's using it and it's inconsistent since adding the whole book doesn't include chapter 0, like we talked about.
I kept whole books being represented as an empty list because it's much more convenient that way for silnlp. Otherwise, we'd have to pass a versification variable through all the different functions just to be able to check chapter counts.
Other than that, I fixed the stuff for backwards ranges and added your test …
=> Clean up get_chapters code and expand tests

machine/scripture/parse.py, tests/scripture/test_parse.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/98)
=> Refactor get_chapters to not reuse code and add additional tests

machine/corpora/corpora_utils.py, machine/corpora/dbl_bundle_text_corpus.py, machine/corpora/file_paratext_project_settings_parser.py, machine/corpora/paratext_backup_terms_corpus.py, machine/corpora/paratext_backup_text_corpus.py, machine/corpora/paratext_project_settings.py, machine/corpora/paratext_project_settings_parser_base.py, machine/corpora/paratext_text_corpus.py, machine/corpora/scripture_text.py, machine/corpora/usfm_file_text_corpus.py, machine/corpora/usfm_parser.py, machine/corpora/usfm_parser_state.py, machine/corpora/usfm_stylesheet.py, machine/corpora/usfm_text_base.py, machine/corpora/usfm_token.py, machine/corpora/usfm_tokenizer.py, machine/corpora/usfm_verse_text_updater.py, machine/corpora/zip_paratext_project_settings_parser.py, machine/corpora/zip_paratext_project_settings_parser_base.py, machine/scripture/verse_ref.py, tests/corpora/test_paratext_project_settings.py, tests/corpora/test_usfm_tokenizer.py, tests/corpora/test_usfm_verse_text_updater.py, tests/scripture/test_versification.py, tests/testutils/data/usfm/Tes/41MATTes.SFM
Based on the changes in Machine from https://github.com/sillsdev/machine/pull/160, I've updated machine.py's handling of USFM accordingly.
Main changes:
1. Files in `machine/corpora` were either created or modified to align with new files/changes in Machine
2. `Versification.load()` in `machine/scripture/verse_ref.py` was updated to accept a stream as input, like it can in Machine
3. Test files were created or modified to reflect new test files/changes in Machine
4. I added a new test case `test_utf_16_encoding_stream()` in `tests/scripture/test_versification.py` to test code I added which handles Unicode errors for loading versification from a stream.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Update machine.py to reflect usfm changes in machine

machine/translation/huggingface/hugging_face_nmt_model_trainer.py, tests/translation/huggingface/test_hugging_face_nmt_model_trainer.py
To account for composite characters, I changed `find_missing_characters()` to normalize the training example before using it to calculate the set of all characters in the training data, rather than normalizing the set of characters.
In addition to the change, I modified one of the test cases for updating the tokenizer to include a check for handling a composite character.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/105)
=> fix normalization order in find_missing_characters()

machine/scripture/parse.py, tests/scripture/test_parse.py
Fix mis-parsing of chapter selections when book name ends in a digit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/106)
=> Parallel to https://github.com/sillsdev/machine/pull/187

.github/workflows/ci.yml
- sil-thot currently doesn't support ARM on MacOS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/109)
=> Use macos-12 GHA runner

machine/translation/huggingface/hugging_face_nmt_model_trainer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/119)
=> small fix for NMT build job

machine/scripture/parse.py, tests/scripture/test_parse.py
get_books now accepts ";" as a delimeter and allows for book ranges, just as get_chapters does.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/122)
=> Updated get_books

machine/corpora/paratext_project_settings_parser_base.py
The reason that `BiblicalTermsListSetting` wasn't allowed to be optional was because the default was set to `""`, but the check to see if a `BiblicalTermsListSetting` exists in the Settings.xml uses `if biblical_terms_list_setting is not None`. I've removed the explicit default so that if it's not found, it assigns `None`, and the subsequent check will work properly. This bug is only in machine.py, not in Machine.
I tested this by temporarily removing the `BiblicalTermsListSetting` line in the `Settings.xml` of the `Tes` folder, and then verifying that the change in defaults successfully changed tests from failing to passing. However, there were a couple tests that depended on the contents of `BiblicalTermsListSetting` not being empty/default, so I had to undo that change in …
=> fix default for BiblicalTermsListSetting

README.md, machine/corpora/__init__.py, machine/corpora/paratext_project_text_updater_base.py, machine/corpora/update_usfm_parser_handler.py, samples/paratext_usfm.ipynb, tests/corpora/test_update_usfm_parser_handler.py, tests/corpora/test_usfm_manual.py
- replace "strip_all_text" and "prefer_existing_text" parameters with a single enum parameter
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/130)
=> Add Paratext/USFM processing tutorial

.vscode/settings.json, README.md, machine/jobs/huggingface/hugging_face_nmt_model_factory.py, machine/jobs/settings.yaml, machine/translation/huggingface/hugging_face_nmt_engine.py, machine/translation/huggingface/hugging_face_nmt_model_trainer.py, machine/translation/translation_suggester.py, machine/translation/truecaser.py, samples/corpora.ipynb, samples/data/smt.cfg, samples/data/sp.txt, samples/machine_translation.ipynb, tests/translation/huggingface/test_hugging_face_nmt_model_trainer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/129)
=> Add MT tutorial

machine/translation/huggingface/hugging_face_nmt_engine.py, poetry.lock, pyproject.toml, samples/machine_translation.ipynb
- update MT tutorial to demonstrate TranslationResult
- incompatible with transformers>=4.42, because of breaking change in NLLB tokenizer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/133)
=> Fix source tokens for HF fast tokenizers

.devcontainer/dockerfile, .github/workflows/ci.yml, dockerfile, dockerfile.cpu_only, machine/corpora/parallel_text_corpus.py, machine/corpora/usfm_text_base.py, machine/jobs/huggingface/hugging_face_nmt_model_factory.py, machine/jobs/nmt_engine_build_job.py, machine/jobs/smt_engine_build_job.py, machine/jobs/word_alignment_build_job.py, machine/translation/huggingface/hugging_face_nmt_engine.py, machine/translation/huggingface/hugging_face_nmt_model_trainer.py, machine/translation/thot/thot_smt_model_trainer.py, poetry.lock, pyproject.toml, tests/translation/huggingface/test_hugging_face_nmt_engine.py, tests/translation/huggingface/test_hugging_face_nmt_model_trainer.py
-Updated machine.py to support Python 3.9-3.12
-Updated Ubuntu version to noble (24.04), along with CUDA version to match Ubuntu
-Updated dev docker container to Python 3.9 and Ubuntu noble
-Updated non-dev docker container to Python 3.12 and Ubuntu noble
-Updated CI to build and test Python 3.9-3.12
-Updated transformers support to versions ">=4.38.0,<4.46"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/131)
=> Update to support Python 3.9-3.12

machine/corpora/__init__.py, machine/corpora/usx_file_alignment_collection.py, machine/corpora/usx_memory_text.py, machine/corpora/usx_token.py, machine/corpora/usx_verse.py, machine/corpora/usx_verse_parser.py, tests/corpora/test_usx_memory_text.py
- Fix incorrect handling of descriptive titles
- Add support for tables
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/138)
=> Fix USX corpus issues

machine/translation/huggingface/__init__.py, machine/translation/huggingface/hugging_face_nmt_engine.py, machine/translation/huggingface/hugging_face_nmt_model_trainer.py, tests/translation/huggingface/test_hugging_face_nmt_model_trainer.py
This PR removes the lang_code_to_id method in places where it could be used by the NllbTokenizer, due to NllbTokenizer deprecating that method, and keeps it for the tokenizers that still use it. In its place, I compare against `tokenizer.added_tokens_encoder`, since that's what huggingface uses as their check inside their `tokenizer.convert_tokens_to_ids`, which was already being used in the `add_lang_code_to_tokenizer` method for obtaining the lang_id from the lang_code. I also added test cases for each of the different tokenizer types supported by machine.py.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/139)
=> fix deprecated tokenizer methods, add test cases

machine/jobs/settings.yaml
#116
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/117)
=> Update learning rate for #116 and other small error

.github/workflows/ci.yml
I think Thot will also have to be updated. - see #148 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/147)
=> Update to macOS-14

machine/jobs/settings.yaml
This is to apply the temporary fix for the S2 upload issues we were having as per https://github.com/sillsdev/serval/issues/613.  It changes the URL to the "path" URL (instead of the "virtual" one, and since the standard AWS configuration is "auto", it will detect the "path" address type and handle it appropriately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/152)
=> Use S3 path type

machine/jobs/settings.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/154)
=> Hotfix: remove attention implementation

.devcontainer/devcontainer.json, .vscode/settings.json, machine/corpora/__init__.py, machine/corpora/paratext_project_text_updater_base.py, machine/corpora/scripture_ref_usfm_parser_handler.py, machine/corpora/update_usfm_parser_handler.py, machine/corpora/usfm_text_base.py, poetry.lock, pyproject.toml, tests/corpora/test_update_usfm_parser_handler.py, tests/corpora/test_usfm_file_text.py, tests/corpora/test_usfm_manual.py, tests/corpora/test_usfm_memory_text.py, tests/corpora/test_usfm_tokenizer.py, tests/testutils/data/usfm/Tes/41MATTes.SFM
This is a mirror PR to https://github.com/sillsdev/machine/pull/281.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/153)
=> Do not translate markers

machine/corpora/aligned_word_pair.py, tests/corpora/test_aligned_word_pair.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/156)
=> Add confidences to word pair representation

machine/jobs/thot/thot_word_alignment_model_factory.py
The root of some WA E2E failures - I removed the "tm" intermediary directory in Serval but forgot to remove it here and it was failing in a difficult-to-debug way.
Machine.py will need to be re-released once this is through so I can proceed with the Serval-side PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/160)
=> Remove 'tm' intermediate directory

machine/corpora/paratext_project_text_updater_base.py, machine/corpora/scripture_ref_usfm_parser_handler.py, machine/corpora/update_usfm_parser_handler.py, tests/corpora/test_update_usfm_parser_handler.py
Add tests for beginning-of-verse embeds
Fix the embed at beginning issue (https://github.com/sillsdev/serval/issues/636)
Add paragraph marker control (https://github.com/sillsdev/serval/issues/627)
Always preserve \r and \rem
Correct behavior for stripping text behavior (https://github.com/sillsdev/serval/issues/629)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/161)
=> Updates to USFM updater

machine/corpora/aligned_word_pair.py, tests/corpora/test_aligned_word_pair.py
This was causing the function to try to set a translation score for pairs with no extra scores. I can add a test for this if you think that would be good.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/164)
=> Fix colon index check

machine/corpora/update_usfm_parser_handler.py, tests/corpora/test_update_usfm_parser_handler.py
Fixes https://github.com/sillsdev/machine.py/issues/166
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/167)
=> Properly preserve specified markers (matching fix in machine)

machine/corpora/scripture_ref_usfm_parser_handler.py, machine/corpora/update_usfm_parser_handler.py, tests/corpora/test_update_usfm_parser_handler.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/170)
=> Fix handling of implicitly closed char styles when updating USFM

machine/corpora/__init__.py, machine/corpora/place_markers_usfm_update_block_handler.py, machine/jobs/nmt_engine_build_job.py, machine/jobs/translation_file_service.py, tests/corpora/test_place_markers_usfm_update_block_handler.py, tests/jobs/test_nmt_engine_build_job.py, tests/jobs/test_smt_engine_build_job.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/175)
=> Marker placement update block handler

machine/corpora/usfm_text_base.py, tests/corpora/test_usfm_file_text.py, tests/corpora/test_usfm_memory_text.py
- includes empty paragraph markers at end of verse rows when including markers
- fixes #188
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/189)
=> Fix non-verse paragraph row when preceded by empty paragraph

machine/corpora/place_markers_usfm_update_block_handler.py, tests/corpora/test_place_markers_usfm_update_block_handler.py
This prevents the code from erroring out with a confusing error message when verses are out of order.
Plus the other couple of tweaks related to the recent changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/190)
=> Handle out-of-order verses

machine/corpora/place_markers_usfm_update_block_handler.py, tests/corpora/test_place_markers_usfm_update_block_handler.py
Also a small change to not count headers as elements that need to be placed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/198)
=> Fix spacing around end markers

machine/translation/huggingface/hugging_face_nmt_model_trainer.py
Can't we just always pass "src"/"trg" here? 
Fixes https://github.com/sillsdev/serval/issues/707
The issue was here:
https://github.com/sillsdev/machine.py/blob/cd2170615c2b4fef337b47ad2bc760db9aca0899/machine/corpora/parallel_text_corpus.py#L429
When `source_lang` and `target_lang` are equal, the dictionary definition collapses to just one of the items. 
I have yet to test the complete pipeline. But I plan to publish a development docker image and then test E2E through local Serval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/199)
=> Use 'src' and 'trg' mirroring silnlp when src and trg lang codes are equal

machine/corpora/__init__.py, machine/corpora/paratext_project_text_updater_base.py, machine/corpora/place_markers_usfm_update_block_handler.py, machine/corpora/update_usfm_parser_handler.py, machine/corpora/usfm_update_block.py, tests/corpora/test_place_markers_usfm_update_block_handler.py, tests/corpora/test_update_usfm_parser_handler.py, tests/corpora/test_usfm_manual.py, tests/corpora/test_usfm_memory_text.py
Fixes https://github.com/sillsdev/machine.py/issues/193
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/202)
=> Pass metadata through update block

machine/corpora/file_paratext_project_quote_convention_detector.py
This PR adds a class that can detect the quote convention for a Paratext project from a project directory.  This class will primarily be used by SILNLP to detect the quote convention for the source and target projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/224)
=> Detect quote convention from file Paratext project

machine/punctuation_analysis/paratext_project_quote_convention_detector.py, machine/punctuation_analysis/quote_convention_detector.py, machine/punctuation_analysis/text_segment.py, machine/punctuation_analysis/usfm_structure_extractor.py, machine/scripture/canon.py, tests/punctuation_analysis/test_paratext_project_quote_convention_detector.py, tests/punctuation_analysis/test_usfm_structure_extractor.py
Fixes #229.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/machine.py/236)
=> Allow passing a selection of books and chapters to the PT quote detector
